default: &default
  pool: 5
  timeout: 5000
  adapter: postgresql

development:
  pool: 10
  timeout: 5000
  username:
  password:
  adapter: postgresql
  database: reservation_portal

test:
  pool: 5
  timeout: 5000
  username:
  password:
  adapter: postgresql
  database: reservation_portal_test